#!/usr/bin/env python

# example entry.py

import gtk
import gobject
import os




class wp_show_conf():

    def setit(self,widget,dummy):
        path = self.filechooserbutton.get_filename()
        timeout = self.spin_button.get_value_as_int()
        enabled = str(self.check.get_active()).lower()
        depth = self.depth_select.get_value_as_int()
        request='tools/install '+path+' '+str(timeout)+' '+enabled+' '+str(depth)
        os.system(request)

    def __init__(self):
        # create a new window
        window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        window.set_title("Gnome 3 Wallpaper Slideshow")
        window.connect("delete_event", lambda w,e: gtk.main_quit())
        window.set_border_width(5)


        vbox = gtk.VBox(False,3)
        window.add(vbox)

        artwork = gtk.VBox()
        fileimage = 'tools/artwork.png'
        window.set_icon_from_file(fileimage)
        image = gtk.Image()
        image.set_from_file(fileimage)
        artwork.pack_start(image, True, True, 0)
        vbox.pack_start(artwork,True,True,1)

        frame = gtk.Frame()
        vbox.pack_start(frame,True,True,1)
        frame.set_border_width(5)

        table = gtk.Table(4,2)
        table.set_border_width(3)
        table.set_row_spacings(4)
        table.set_col_spacings(6)

        label = gtk.Label(' Path : ')
        label.set_alignment(0, 0.5)
        table.attach(label, 0, 1, 0, 1, gtk.FILL,gtk.FILL | gtk.EXPAND, 0, 0)
        frame.add(table)


        self.filechooserbutton = gtk.FileChooserButton('Browse')
        self.filechooserbutton.set_current_folder('/home')
        self.filechooserbutton.set_tooltip_text('Browse to the folder containing your wallpapers')
        table.attach(self.filechooserbutton, 1, 2, 0, 1, gtk.FILL,gtk.FILL | gtk.EXPAND, 0, 0)
        self.filechooserbutton.set_action(gtk.FILE_CHOOSER_ACTION_SELECT_FOLDER)

        label = gtk.Label(' Timeout : ')
        label.set_alignment(0, 0.5)
        table.attach(label, 0, 1, 1, 2, gtk.FILL,gtk.FILL | gtk.EXPAND, 0, 0)

        adjustment = gtk.Adjustment(100,10,1000,5,10)
        self.spin_button = gtk.SpinButton(adjustment)
        self.spin_button.set_numeric(True)
        self.spin_button.set_tooltip_text('Time between Switch')
        table.attach(self.spin_button, 1, 2, 1, 2, gtk.FILL,gtk.FILL | gtk.EXPAND, 0, 0)
        self.spin_button.show()

        label = gtk.Label(' Directory Depth : ')
        label.set_alignment(0, 0.5)
        table.attach(label, 0, 1, 2, 3, gtk.FILL,gtk.FILL | gtk.EXPAND, 0, 0)

        adjustment1 = gtk.Adjustment(3,1,10,1,1)
        self.depth_select = gtk.SpinButton(adjustment1)
        self.depth_select.set_numeric(True)
        self.depth_select.set_tooltip_text('Level to which the sub-folder must be scanned')
        table.attach(self.depth_select, 1, 2, 2, 3, gtk.FILL,gtk.FILL | gtk.EXPAND, 0, 0)

        label = gtk.Label(' Enable / Disable : ')
        label.set_alignment(0, 0.5)
        table.attach(label, 0, 1, 3, 4, gtk.FILL,gtk.FILL | gtk.EXPAND, 0, 0)

        self.check = gtk.CheckButton()
        self.check.set_tooltip_text('Enable or disable the Slideshow')
        self.check.set_active(True)
        table.attach(self.check, 1, 2, 3, 4)

        frame = gtk.Frame ()
        hbox = gtk.HBox(True)
        frame.add(hbox)
        vbox.pack_start(frame, False, True, 0)
        hbox.show()


        button = gtk.Button(stock=gtk.STOCK_CLOSE)
        button.connect("clicked", lambda w: gtk.main_quit())
        hbox.pack_start(button, False, True, 0)
        button.set_flags(gtk.CAN_DEFAULT)
        button.grab_default()

        button = gtk.Button(stock=gtk.STOCK_APPLY)
        button.connect("clicked", self.setit,None)
        hbox.pack_start(button, False, True, 0)
        
        frame = gtk.Frame ('Developed By: ') 
        label = gtk.Label(' Dhananjay Sathe : dhananjaysathe@gmail.com')
        label.set_alignment(0.4, 0.1)
        frame.add(label)
        vbox.pack_start(frame, False, True, 0)


        window.show_all()


def main():
    gtk.main()
    return 0

if __name__ == "__main__":
    wp_show_conf()
    main()
