#! /bin/bash
#Dhananjay Sathe : dhananjaysathe@gmail.com
#http://dsathe.blogspot.com/

print_msg()
{
	echo "wp-show: " $1
}

cd tools
timeout=$1
enabled=$2
depth=$3
shift;shift;shift
base=$@

string='#! /bin/bash \nbase="'${base}'"\ntimeout='${timeout}'\nenabled='${enabled}'\ndepth='${depth}'\n'

dir="$HOME/.wp-show"
if [[ ! -e $dir ]]; then
    mkdir $dir
fi
echo -e $string > "$HOME/.wp-show/wp-show"
cat wp-show >> "$HOME/.wp-show/wp-show"
if $enabled
 	then
		print_msg "Enabling wp-show."
		print_msg "Killing GUI."
		killall -9 wp-show
		chmod a+x $HOME/.wp-show/wp-show
		$HOME/.wp-show/wp-show &
		cp wp-show.desktop $HOME/.config/autostart/wp-show.desktop
		string2=Exec=$HOME/.wp-show/wp-show
		echo $string2 >>"$HOME/.config/autostart/wp-show.desktop"
	else 
		print_msg "Disabling wp-show."
		chmod -x $HOME/.wp-show/wp-show
		print_msg "Killing GUI."
		killall -9 wp-show
		rm $HOME/.wp-show/wp-show
		rm $HOME/.config/autostart/wp-show.desktop
		print_msg "Done."
fi
